#%RAML 1.0 DataType

type: array
items:
  type: object
  properties:
    ERPCountryAssignment__c?: string
    Id?: string
    IsDeleted?: boolean
    MasterRecordId?: string
    Name?: string
    Type?: string
    RecordTypeId?: string
    ParentId?: string
    BillingStreet?: string
    BillingCity?: string
    BillingState?: string
    BillingPostalCode?: string
    BillingCountry?: string
    BillingStateCode?: string
    BillingCountryCode?: string
    BillingLatitude?: number
    BillingLongitude?: number
    BillingGeocodeAccuracy?: string
    ShippingStreet?: string
    ShippingCity?: string
    ShippingState?: string
    ShippingPostalCode?: string
    ShippingCountry?: string
    ShippingStateCode?: string
    ShippingCountryCode?: string
    ShippingLatitude?: number
    ShippingLongitude?: number
    ShippingGeocodeAccuracy?: string
    Phone?: string
    Fax?: string
    Website?: string
    PhotoUrl?: string
    Industry?: string
    NumberOfEmployees?: number
    Description?: string
    CurrencyIsoCode?: string
    OwnerId?: string
    CreatedDate?: string
    CreatedById?: string
    LastModifiedDate?: string
    LastModifiedById?: string
    SystemModstamp?: string
    LastActivityDate?: string
    LastViewedDate?: string
    LastReferencedDate?: string
    IsCustomerPortal?: boolean
    Jigsaw?: string
    JigsawCompanyId?: string
    AccountSource?: string
    SicDesc?: string
    TaxNumber__c?: number
    SpecialInformation__c?: string
    AccountName2__c?: string
    OpenOpportunities__c?: number
    PrimaryContact__c?: string
    WarrantyTimes__c?: string
    Discounts__c?: string
    Show_Flow__c?: boolean
    AccountGUID__c?: string
    MarketKeyCode__c?: string
    ApplicationKeyCodeAPC__c?: string
    TypeOfCustomerTOC__c?: string
    Email__c?: string
    test__c?: string
    Potential__c?: number
    DC1CustomerClassification__c?: string
    DC2CustomerClassification__c?: string
    DC3CustomerClassification__c?: string
    DC4CustomerClassification__c?: string
    DC1WarrantyTimes__c?: string
    DC2WarrantyTimes__c?: string
    DC3WarrantyTimes__c?: string
    DC4WarrantyTimes__c?: string
    DC1PaymentConditions__c?: string
    DC2_Payment_Conditions__c?: string
    DC3PaymentConditions__c?: string
    DC4PaymentConditions__c?: string
    DC1DeliveryConditions__c?: string
    DC2DeliveryConditions__c?: string
    DC3DeliveryConditions__c?: string
    DC4DeliveryConditions__c?: string
    DC1Discount__c?: string
    DC2Discount__c?: string
    DC3Discount__c?: string
    DC4Discount__c?: string
    HasChineseCharacters__c?: string
    VATNumber__c?: string
    SearchTerm__c?: string
    
        
    
    
    
    
    
    
    