#%RAML 1.0 DataType

type: array
items:
  type: object
  properties:
    Id?: string
    ContactId?: string
    AccountId?: string
    ParentId?: string
    RootAssetId?: string
    Product2Id?: string
    ProductCode?: string
    ProductFamily?: string
    ProductDescription?: string
    IsCompetitorProduct?: boolean
    CreatedDate?: string
    CreatedById?: string
    LastModifiedDate?: string
    LastModifiedById?: string
    SystemModstamp?: string
    IsDeleted?: boolean
    CurrencyIsoCode?: string
    Name?: string
    SerialNumber?: string
    InstallDate?: string
    ManufactureDate?: string
    StatusReason?: string
    Uuid?: string
    ExternalIdentifier?: string
    PurchaseDate?: string
    UsageEndDate?: string
    Status?: string
    DigitalAssetStatus?: string
    Price?: number
    Quantity?: number
    Description?: string
    OwnerId?: string
    RecordTypeId?: string
    LocationId?: string
    AssetProvidedById?: string
    AssetServicedById?: string
    IsInternal?: boolean
    AssetLevel?: number
    StockKeepingUnit?: string
    LastViewedDate?: string
    LastReferencedDate?: string
    Accessories__c?: string
    MotorApproval__c?: string
    MotorDrive__c?: string
    NominalOutput50Hz__c?: string
    NominalOutput60Hz__c?: string
    OperatingMode__c?: string
    Paintwork__c?: string
    PressureSideConnection__c?: string
    ProtectionClassEN60529__c?: string
    SuctionSideConnection__c?: string
    TemperatureControl__c?: string
    Type__c?: string
    Voltage__c?: string
    CurrentAssignment__c?: boolean
    AssetGUID__c?: string
    Modifications__c?: string
    OrderNumber__c?: string
    WarrantyTime__c?: string
    









