#%RAML 1.0 DataType

type: array
items:
  type: object
  properties:
    ERPCountryAssignment__c?: string
    Id?: string
    IsDeleted?: boolean
    MasterRecordId?: string
    AccountId?: string
    LastName?: string
    FirstName?: string
    Salutation?: string
    Name?: string
    MailingStreet?: string
    MailingCity?: string
    MailingState?: string
    MailingPostalCode?: string
    MailingCountry?: string
    MailingStateCode?: string
    MailingCountryCode?: string
    MailingLatitude?: number
    MailingLongitude?: number
    MailingGeocodeAccuracy?: string
    Phone?: string
    Fax?: string
    MobilePhone?: string
    ReportsToId?: string
    Email?: string
    Title?: string
    Department__c?: string
    CurrencyIsoCode?: string
    OwnerId?: string
    CreatedDate?: string
    CreatedById?: string
    LastModifiedDate?: string
    LastModifiedById?: string
    SystemModstamp?: string
    LastActivityDate?: string
    LastCURequestDate?: string
    LastCUUpdateDate?: string
    LastViewedDate?: string
    LastReferencedDate?: string
    EmailBouncedReason?: string
    EmailBouncedDate?: string
    IsEmailBounced?: boolean
    PhotoUrl?: string
    Jigsaw?: string
    JigsawContactId?: string
    IndividualId?: string
    AdvertisingMail__c?: boolean
    ContactGUID__c?: string
    PrimaryAccountContact__c?: boolean
    








 