#%RAML 1.0 DataType

type: array
items:
  type: object
  properties:
    Id?: string
    OwnerId?: string
    ContractId?: string
    AccountId?: string
    Pricebook2Id?: string
    OriginalOrderId?: string
    EffectiveDate?: string
    EndDate?: string
    IsReductionOrder?: boolean
    Status?: string
    Description?: string
    CustomerAuthorizedById?: string
    CompanyAuthorizedById?: string
    Type?: string
    BillingStreet?: string
    BillingCity?: string
    BillingState?: string
    BillingPostalCode?: string
    BillingCountry?: string
    BillingStateCode?: string
    BillingCountryCode?: string
    BillingLatitude?: number
    BillingLongitude?: number
    BillingGeocodeAccuracy?: string
    ShippingStreet?: string
    ShippingCity?: string
    ShippingState?: string
    ShippingPostalCode?: string
    ShippingCountry?: string
    ShippingStateCode?: string
    ShippingCountryCode?: string
    ShippingLatitude?: number
    ShippingLongitude?: number
    ShippingGeocodeAccuracy?: string
    ActivatedDate?: string
    ActivatedById?: string
    StatusCode?: string
    CurrencyIsoCode?: string
    SalesAgreementId?: string
    OrderNumber?: string
    TotalAmount?: number
    CreatedDate?: string
    CreatedById?: string
    LastModifiedDate?: string
    LastModifiedById?: string
    IsDeleted?: boolean
    SystemModstamp?: string
    LastViewedDate?: string
    LastReferencedDate?: string
    
        



   