#%RAML 1.0 DataType

type: array
items:
  type: object
  properties:
    Id?: string
    Name?: string
    ProductCode?: string
    Description?: string
    IsActive?: boolean
    CreatedDate?: string
    CreatedById?: string
    LastModifiedDate?: string
    LastModifiedById?: string
    SystemModstamp?: string
    Family?: string
    CurrencyIsoCode?: string
    ExternalDataSourceId?: string
    ExternalId?: string
    DisplayUrl?: string
    QuantityUnitOfMeasure?: string
    IsDeleted?: boolean
    IsArchived?: boolean
    LastViewedDate?: string
    LastReferencedDate?: string
    StockKeepingUnit?: string
    ProductGUID__c?: string
    Type__c?: string
    WeightInKG__c?: number
    CustomsTariffNumber__c?: string
    MotorDrive__c?: string
    NominalOutput50Hz__c?: string
    NominalOutput60Hz__c?: string
    Paintwork__c?: string
    PressureSideConnection__c?: string
    ProtectionClassEN60529__c?: string
    SuctionSideConnection__c?: string
    TemperatureControl__c?: string
    Voltage__c?: string
    OperatingMode__c?: string
    Construction__c?: string
    MotorApprobation__c?: string
    Accessories__c?: string
    







   