#%RAML 1.0 Library

types:
  account: !include ../Types/account.raml
  asset: !include ../Types/asset.raml
  contact: !include ../Types/contact.raml
  order: !include ../Types/order.raml
  product2: !include ../Types/product2.raml 
  quote: !include ../Types/quote.raml
