#%RAML 1.0 Library

resourceTypes:
  apiStatus: !include ../Endpoints/apiStatusResource.raml
  account: !include ../Endpoints/accountResource.raml
  asset: !include ../Endpoints/assetResource.raml
  contact: !include ../Endpoints/contactResource.raml
  order: !include ../Endpoints/orderResource.raml
  product2: !include ../Endpoints/product2Resource.raml
  quote: !include ../Endpoints/quoteResource.raml