#%RAML 1.0 NamedExample

statusCode: 201
statusType: "Created"
statusMessage: "The request has been fulfilled, resulting in the creation of a new resource."
statusDetails: "The requested action carried out successfully."