#%RAML 1.0 NamedExample

statusCode: 401
statusType: "Unauthorized"
statusMessage: "No credentials are provided or provided credentials are refused."
statusDetails: "Missing or unvalid credentials. Please provide valid credentials."