#%RAML 1.0 NamedExample

statusCode: 403
statusType: "Forbidden"
statusMessage: "User is not allowed to perform the requested operation."
statusDetails: "User is not allowed to perform the requested operation."