#%RAML 1.0 NamedExample

statusCode: 404
statusType: "Resource does not exists"
statusMessage: "The requested URI does not map to a resource."
statusDetails: "The requested resource could not be found but may be available again in the future."