#%RAML 1.0 NamedExample

[
  {  
    "Id": "example",
    "IsDeleted": true,
    "MasterRecordId": "example",
    "Name": "example",
    "Type": "example",
    "RecordTypeId": "example",
    "ParentId": "example",
    "BillingStreet": "example",
    "BillingCity": "example",
    "BillingState": "example",
    "BillingPostalCode": "example",
    "BillingCountry": "example",
    "BillingStateCode": "example",
    "BillingCountryCode": "example",
    "BillingLatitude": 0,
    "BillingLongitude": 0,
    "BillingGeocodeAccuracy": "example",
    "ShippingStreet": "example",
    "ShippingCity": "example",
    "ShippingState": "example",
    "ShippingPostalCode": "example",
    "ShippingCountry": "example",
    "ShippingStateCode": "example",
    "ShippingCountryCode": "example",
    "ShippingLatitude": 0,
    "ShippingLongitude": 0,
    "ShippingGeocodeAccuracy": "example",
    "Phone": "example",
    "Fax": "example",
    "Website": "example",
    "PhotoUrl": "example",
    "Industry": "example",
    "NumberOfEmployees": 0,
    "Description": "example",
    "CurrencyIsoCode": "example",
    "OwnerId": "example",
    "CreatedDate": "2021-07-09T07:59:19.000Z",
    "CreatedById": "example",
    "LastModifiedDate": "2021-07-09T07:59:19.000Z",
    "LastModifiedById": "example",
    "SystemModstamp": "2021-07-09T07:59:19.000Z",
    "LastActivityDate": "2021-07-09",
    "LastViewedDate": "2021-07-09T07:59:19.000Z",
    "LastReferencedDate": "2021-07-09T07:59:19.000Z",
    "IsCustomerPortal": true,
    "Jigsaw": "example",
    "JigsawCompanyId": "example",
    "AccountSource": "example",
    "SicDesc": "example",
    "TaxNumber__c": 0,
    "SpecialInformation__c": "example",
    "AccountName2__c": "example",
    "OpenOpportunities__c": 0,
    "PrimaryContact__c": "example",
    "WarrantyTimes__c": "example",
    "Discounts__c": "example",
    "Show_Flow__c": true,
    "AccountGUID__c": "example",
    "MarketKeyCode__c": "example",
    "ApplicationKeyCodeAPC__c": "example",
    "TypeOfCustomerTOC__c": "example",
    "Email__c": "example@gmail.com",
    "test__c": "example",
    "Potential__c": 0,
    "DC1CustomerClassification__c": "example",
    "DC2CustomerClassification__c": "example",
    "DC3CustomerClassification__c": "example",
    "DC4CustomerClassification__c": "example",
    "DC1WarrantyTimes__c": "example",
    "DC2WarrantyTimes__c": "example",
    "DC3WarrantyTimes__c": "example",
    "DC4WarrantyTimes__c": "example",
    "DC1PaymentConditions__c": "example",
    "DC2_Payment_Conditions__c": "example",
    "DC3PaymentConditions__c": "example",
    "DC4PaymentConditions__c": "example",
    "DC1DeliveryConditions__c": "example",
    "DC2DeliveryConditions__c": "example",
    "DC3DeliveryConditions__c": "example",
    "DC4DeliveryConditions__c": "example",
    "DC1Discount__c": "example",
    "DC2Discount__c": "example",
    "DC3Discount__c": "example",
    "DC4Discount__c": "example",
    "HasChineseCharacters__c": "example",
    "VATNumber__c": "example",
    "SearchTerm__c": "example"  
  } 
]
    

