#%RAML 1.0 NamedExample
apiStatusExample: [
  {
    "application": {
        "name": "becker"
    },
    "api": {
        "domain": "example",
        "name": "example",
        "id": "example",
        "version": "example"
       },
    "environment": {
        "name": "example"
    },
    "status": {
        "result": "pass",
        "details": "API is healthy"
    },
    "timestamp": "now()"
}

]
    
