#%RAML 1.0 NamedExample

[
  {
    "Id": "example",
    "ContactId": "example",
    "AccountId": "example",
    "ParentId": "example",
    "RootAssetId": "example",
    "Product2Id": "example",
    "ProductCode": "example",
    "ProductFamily": "example",
    "ProductDescription": "example",
    "IsCompetitorProduct": true,
    "CreatedDate": "2021-07-09T07:59:19.000Z",
    "CreatedById": "example",
    "LastModifiedDate": "2021-07-09T07:59:19.000Z",
    "LastModifiedById": "example",
    "SystemModstamp": "2021-07-09T07:59:19.000Z",
    "IsDeleted": true,
    "CurrencyIsoCode": "example",
    "Name": "example",
    "SerialNumber": "example",
    "InstallDate": "2021-07-09",
    "ManufactureDate": "2021-07-09",
    "StatusReason": "example",
    "Uuid": "example",
    "ExternalIdentifier": "example",
    "PurchaseDate": "2021-07-09",
    "UsageEndDate": "2021-07-09",
    "Status": "example",
    "DigitalAssetStatus": "example",
    "Price": 0,
    "Quantity": 0,
    "Description": "example",
    "OwnerId": "example",
    "RecordTypeId": "example",
    "LocationId": "example",
    "AssetProvidedById": "example",
    "AssetServicedById": "example",
    "IsInternal": true,
    "AssetLevel": 0,
    "StockKeepingUnit": "example",
    "LastViewedDate": "2021-07-09T07:59:19.000Z",
    "LastReferencedDate": "2021-07-09T07:59:19.000Z",
    "Accessories__c": "example",
    "MotorApproval__c": "example",
    "MotorDrive__c": "example",
    "NominalOutput50Hz__c": "example",
    "NominalOutput60Hz__c": "example",
    "OperatingMode__c": "example",
    "Paintwork__c": "example",
    "PressureSideConnection__c": "example",
    "ProtectionClassEN60529__c": "example",
    "SuctionSideConnection__c": "example",
    "TemperatureControl__c": "example",
    "Type__c": "example",
    "Voltage__c": "example",
    "CurrentAssignment__c": true,
    "AssetGUID__c": "example",
    "Modifications__c": "example",
    "OrderNumber__c": "example",
    "WarrantyTime__c": "example"
  }
]