#%RAML 1.0 NamedExample

[
  {
    "Id": "example",
    "IsDeleted": true,
    "MasterRecordId": "example",
    "AccountId": "example",
    "LastName": "example",
    "FirstName": "example",
    "Salutation": "example",
    "Name": "example",
    "MailingStreet": "example",
    "MailingCity": "example",
    "MailingState": "example",
    "MailingPostalCode": "example",
    "MailingCountry": "example",
    "MailingStateCode": "example",
    "MailingCountryCode": "example",
    "MailingLatitude": 0,
    "MailingLongitude": 0,
    "MailingGeocodeAccuracy": "example",
    "Phone": "example",
    "Fax": "example",
    "MobilePhone": "example",
    "ReportsToId": "example",
    "Email": "example@gmail.com",
    "Title": "example",
    "Department__c": "example",
    "CurrencyIsoCode": "example",
    "OwnerId": "example",
    "CreatedDate": "2021-07-09T07:59:19.000Z",
    "CreatedById": "example",
    "LastModifiedDate": "2021-07-09T07:59:19.000Z",
    "LastModifiedById": "example",
    "SystemModstamp": "2021-07-09T07:59:19.000Z",
    "LastActivityDate": "2021-07-09",
    "LastCURequestDate": "2021-07-09T07:59:19.000Z",
    "LastCUUpdateDate": "2021-07-09T07:59:19.000Z",
    "LastViewedDate": "2021-07-09T07:59:19.000Z",
    "LastReferencedDate": "2021-07-09T07:59:19.000Z",
    "EmailBouncedReason": "example",
    "EmailBouncedDate": "2021-07-09T07:59:19.000Z",
    "IsEmailBounced": true,
    "PhotoUrl": "example",
    "Jigsaw": "example",
    "JigsawContactId": "example",
    "IndividualId": "example",
    "AdvertisingMail__c": true,
    "ContactGUID__c": "example",
    "PrimaryAccountContact__c": true
  }  
]