#%RAML 1.0 NamedExample
  
[
  {
    "Id": "example",
    "OwnerId": "example",
    "ContractId": "example",
    "AccountId": "example",
    "Pricebook2Id": "example",
    "OriginalOrderId": "example",
    "EffectiveDate": "2021-07-09",
    "EndDate": "2021-07-09",
    "IsReductionOrder": true,
    "Status": "example",
    "Description": "example",
    "CustomerAuthorizedById": "example",
    "CompanyAuthorizedById": "example",
    "Type": "example",
    "BillingStreet": "example",
    "BillingCity": "example",
    "BillingState": "example",
    "BillingPostalCode": "example",
    "BillingCountry": "example",
    "BillingStateCode": "example",
    "BillingCountryCode": "example",
    "BillingLatitude": 0,
    "BillingLongitude": 0,
    "BillingGeocodeAccuracy": "example",
    "ShippingStreet": "example",
    "ShippingCity": "example",
    "ShippingState": "example",
    "ShippingPostalCode": "example",
    "ShippingCountry": "example",
    "ShippingStateCode": "example",
    "ShippingCountryCode": "example",
    "ShippingLatitude": 0,
    "ShippingLongitude": 0,
    "ShippingGeocodeAccuracy": "example",
    "ActivatedDate": "2021-07-09T07:59:19.000Z",
    "ActivatedById": "example",
    "StatusCode": "example",
    "CurrencyIsoCode": "example",
    "SalesAgreementId": "example",
    "OrderNumber": "example",
    "TotalAmount": 0,
    "CreatedDate": "2021-07-09T07:59:19.000Z",
    "CreatedById": "example",
    "LastModifiedDate": "2021-07-09T07:59:19.000Z",
    "LastModifiedById": "example",
    "IsDeleted": true,
    "SystemModstamp": "2021-07-09T07:59:19.000Z",
    "LastViewedDate": "2021-07-09T07:59:19.000Z",
    "LastReferencedDate": "2021-07-09T07:59:19.000Z"
  }
]