#%RAML 1.0 NamedExample

[
  {
    "Id": "example",
    "Name": "example",
    "ProductCode": "example",
    "Description": "example",
    "IsActive": true,
    "CreatedDate": "2021-07-09T07:59:19.000Z",
    "CreatedById": "example",
    "LastModifiedDate": "2021-07-09T07:59:19.000Z",
    "LastModifiedById": "example",
    "SystemModstamp": "2021-07-09T07:59:19.000Z",
    "Family": "example",
    "CurrencyIsoCode": "example",
    "ExternalDataSourceId": "example",
    "ExternalId": "example",
    "DisplayUrl": "example",
    "QuantityUnitOfMeasure": "example",
    "IsDeleted": true,
    "IsArchived": true,
    "LastViewedDate": "2021-07-09T07:59:19.000Z",
    "LastReferencedDate": "2021-07-09T07:59:19.000Z",
    "StockKeepingUnit": "example",
    "ProductGUID__c": "example",
    "Type__c": "example",
    "WeightInKG__c": 0,
    "CustomsTariffNumber__c": "example",
    "MotorDrive__c": "example",
    "NominalOutput50Hz__c": "example",
    "NominalOutput60Hz__c": "example",
    "Paintwork__c": "example",
    "PressureSideConnection__c": "example",
    "ProtectionClassEN60529__c": "example",
    "SuctionSideConnection__c": "example",
    "TemperatureControl__c": "example",
    "Voltage__c": "example",
    "OperatingMode__c": "example",
    "Construction__c": "example",
    "MotorApprobation__c": "example",
    "Accessories__c": "example"
  }
]