#%RAML 1.0 NamedExample

[
  {
    "Id": "example",  
    "IsDeleted": true,
    "Name": "example",
    "CurrencyIsoCode": "example",
    "CreatedDate": "2021-07-09T07:59:19.000Z",
    "CreatedById": "example",
    "LastModifiedDate": "2021-07-09T07:59:19.000Z",
    "LastModifiedById": "example",
    "SystemModstamp": "2021-07-09T07:59:19.000Z",
    "LastViewedDate": "2021-07-09T07:59:19.000Z",
    "LastReferencedDate": "2021-07-09T07:59:19.000Z",
    "Opportunity__c": "example",
    "Account__c": "example",
    "BillingAccount__c": "example",
    "Order__c": "example",
    "Discount__c": 0,
    "Tax__c": 0,
    "ShippingandHandling__c": 0,
    "Status__c": "example",
    "IsPrimary__c": true,
    "ExpirationDate__c": "2021-07-09",
    "DocumentLanguage__c": "example",
    "QuotePersonalIntroduction__c": "example",
    "Description__c": "example",
    "QuoteNumber__c": "example",
    "ContactName__c": "example",
    "Email__c": "example@gmail.com",
    "Phone__c": "example",
    "Subtotal__c": 0,
    "TotalPrice__c": 0,
    "GrandTotal__c": 0,
    "QuoteGUID__c": "example",
    "AccountGUID__c": "DE-4711",
      "lineItems":
        [
          {
            "Id": "example",  
            "IsDeleted": true,
            "Name": "example",
            "CurrencyIsoCode": "example",
            "CreatedDate": "2021-07-09T07:59:19.000Z",
            "CreatedById": "example",
            "LastModifiedDate": "2021-07-09T07:59:19.000Z",
            "LastModifiedById": "example",
            "SystemModstamp": "2021-07-09T07:59:19.000Z",
            "LastActivityDate": "2021-07-09",
            "LastViewedDate": "2021-07-09T07:59:19.000Z",
            "LastReferencedDate": "2021-07-09T07:59:19.000Z",
            "Product__c": "example",
            "SalesPrice__c": 0,
            "Quantity__c": 0,
            "Description__c": "example",
            "Subtotal__c": 0,
            "Discount__c": 0,
            "TotalPrice__c": 0,
            "Quote__c": "example",
            "QuoteLineItemGUID__c": "exampl"
          }
        ] 
  }
]

