#%RAML 1.0 DocumentationItem
title: SapiSalesforceBecker
content:
   > 
   >System API for __update__: 
        
      * _account_
      * _asset_ 
      * _contact_
      * _order_
      * _product2_
      * _quote_
      
   >and __receiving calls__ from salesforce for:

      * _account_
      * _contact_
      * _quote_






    